#development version
version: '3'

services:
    kafka:
      build:
        context: ./docker/kafka-zookeeper
        dockerfile: Dockerfile
        args:
          SCALA_VERSION: "2.11"
          KAFKA_VERSION: "0.10.2.1"
      container_name: kafka_server_1
      hostname: kafka_server_1
      ports:
        - "9092:9092"

    php_app:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
        args:
          LIBRDKAFKA: "v0.9.5"
      volumes:
        - ./src:/var/www/html
      links:
        - kafka
      container_name: kafka_php_1
      hostname: kafka_php_1

